name: build-windows

on:
  workflow_dispatch:
  push:
    paths:
      - "**"
      - ".github/workflows/windows.yml"

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Publish portable x64 exe
        run: dotnet publish .\src\NevaVision\NevaVision.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: NevaVision-win-x64
          path: src/NevaVision/bin/Release/net8.0-windows/win-x64/publish/
